# Generated by Django 5.1.7 on 2025-04-08 21:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workout", "0002_tag_workout_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workout",
            name="tag",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
