# Generated by Django 5.1.7 on 2025-03-31 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0008_alter_userprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="mantra",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="name",
            field=models.CharField(blank=True, default="test-username", max_length=100),
            preserve_default=False,
        ),
    ]
