name: Lint

on:
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          use_pyproject: true
