[tool.black]
required-version = "25.1.0"
line-length = 88
target-version = ['py39']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | env
  | venv
  | static
  | migrations
  | __pycache__
)/
'''